name: Dependabot Manager

on:
  workflow_dispatch:
    inputs:
      USER_MODE:
        description: "True if personal repos, False for organization repos"
        required: false
        default: "true"
      ORG_NAME:
        description: "Name of the organization (if USER_MODE=false)"
        required: false
        default: "yourorg"
      MY_NAME:
        description: "Your name for co-authored merges"
        required: false
        default: "Arpit Jain"
      MY_EMAIL:
        description: "Your email for co-authored merges"
        required: false
        default: "3242828+arpitjain099@users.noreply.github.com"

  schedule:
    - cron: "5 1 * * 0"  # Sunday 01:05 UTC

jobs:
  manage-dependabot:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      # 4) Run the script
      - name: Run Dependabot Manager Script
        run: |
          python dependency-fix.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          
          # Take inputs from the manual run (if provided). If not manual, defaults apply
          USER_MODE: ${{ github.event.inputs.USER_MODE || 'true' }}
          ORG_NAME: ${{ github.event.inputs.ORG_NAME || 'yourorg' }}
          MY_NAME: ${{ github.event.inputs.MY_NAME || 'Arpit Jain' }}
          MY_EMAIL: ${{ github.event.inputs.MY_EMAIL || '3242828+arpitjain099@users.noreply.github.com' }}

          # Additional environment overrides if desired:
          ENABLE_STEP_SYNC_FORKS: "true"
          ENABLE_STEP_ENABLE_DEPENDABOT: "true"
          ENABLE_STEP_MERGE_DEPENDABOT_PRS: "true"
          TIMEOUT_SECONDS: "30"
          POLL_INTERVAL_SECONDS: "10"
          MERGE_METHOD: "merge"
          COUNT_MERGES_AS_PERSONAL_COMMITS: "true"
