name: Dependabot Manager

on:
  workflow_dispatch:
    inputs:
      USER_MODE:
        description: "True if personal repos, False for organization repos"
        required: false
        default: "true"
      ORG_NAME:
        description: "Name of the organization (if USER_MODE=false)"
        required: false
        default: "YourOrgName"
      MY_NAME:
        description: "Your name for co-authored merges"
        required: false
        default: "YourName"
      MY_EMAIL:
        description: "Your GitHub email for co-authored merges"
        required: false
        default: "YourGitHubEmail"

  schedule:
    - cron: "0 0 * * *"  # Daily 00:00 UTC

jobs:
  manage-dependabot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run Dependabot Manager Script
        run: |
          python dependency-fix.py
        env:
          # Provide the GitHub token from your repository's secret
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

          # Take inputs from the manual run or default to fallback
          USER_MODE: ${{ github.event.inputs.USER_MODE || 'true' }}
          ORG_NAME: ${{ github.event.inputs.ORG_NAME || 'YourOrgName' }}
          MY_NAME: ${{ github.event.inputs.MY_NAME || 'YourName' }}
          MY_EMAIL: ${{ github.event.inputs.MY_EMAIL || '3242828+arpitjain099@users.noreply.github.com' }}

          # Additional environment overrides
          ENABLE_STEP_SYNC_FORKS: "true"
          ENABLE_STEP_ENABLE_DEPENDABOT: "true"
          ENABLE_STEP_MERGE_DEPENDABOT_PRS: "true"
          TIMEOUT_SECONDS: "30"
          POLL_INTERVAL_SECONDS: "10"
          MERGE_METHOD: "merge"
          COUNT_MERGES_AS_PERSONAL_COMMITS: "true"
